In [12]:
import pandas as pd

In [14]:
season1 = pd.read_csv("data/2020-2021.csv")

In [15]:
season1.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,1,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,0,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,2,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97

In [16]:
season1.shape

(380, 106)

In [17]:
season1["HomeTeam"].value_counts()

Fulham              19
Crystal Palace      19
Burnley             19
Wolves              19
Aston Villa         19
Leicester           19
Chelsea             19
Newcastle           19
Southampton         19
Arsenal             19
Man United          19
Leeds               19
Everton             19
Sheffield United    19
Brighton            19
Tottenham           19
West Brom           19
West Ham            19
Liverpool           19
Man City            19
Name: HomeTeam, dtype: int64